### PR TITLE
add variables for mailer configuration

### PR DESCRIPTION
**Pull request by batpad**
@geohacker can you look? I'm a bit unsure how the variables get from Github secrets -> the environment the docker-compose is run in.

### CODE REVIEW

**Comment by batpad** [comment]
+cc @Rub21

**Comment by batpad** [comment]
Ah my bad - I see I just need to add them here: https://github.com/hotosm/tf-azure-osm-seed/blob/main/.github/workflows/deploy.yml#L18 - will do that.

**Comment by batpad** [comment]
Ok, we will need to add the following secrets:

 - `MAILER_ADDRESS` (hostname of smtp server)
 - `MAILER_DOMAIN` (the domain the email should originate from)
 - `MAILER_FROM` (from address for emails sent)
 - `MAILER_USERNAME` (username for smtp server)
 - `MAILER_PASSWORD` (password for smtp server)
 - `MAILER_PORT` (smtp port to use)

Can discuss and clarify what each one needs to be on call. cc @Rub21 @dakotabenjamin @geohacker

**Review by geohacker — APPROVED** [review]
@batpad should we add the variables into production/main.tf as well?

**Comment by batpad** [comment]
> @batpad should we add the variables into production/main.tf as well?

Oh, I thought I had - thanks for the catch, adding.

**Pull request merged**
